In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import silhouette_score
from numpy import savetxt
import pandas as pd
from sklearn.metrics.cluster import normalized_mutual_info_score
from sklearn.metrics import f1_score
from csv import writer
from google.colab import files
from sklearn.metrics.cluster import adjusted_rand_score

In [ ]:
POLE_data= np.loadtxt("highland_undirected.embedding")
df = pd.DataFrame(POLE_data);
#del df[0];

In [ ]:
## txt load
# graph 

In [ ]:
df.shape

(16, 4)

In [ ]:
df

0         1         2         3
0   0.424019  0.314390  0.171025  2.712381
1   0.250439  0.321740 -0.674131  2.353318
2  -0.203921 -0.370838 -0.380530 -1.772717
3  -0.078802 -0.265832 -0.226137 -0.885317
4  -0.064915  0.438161  1.092724 -1.580817
5  -0.016882  0.285393 -1.068567 -2.027799
6   0.231370  0.193363 -0.251585 -1.570515
7   0.305894 -0.313771 -1.044863 -1.561229
8   0.337618 -0.174567  1.724630 -0.581566
9   0.337390 -0.188121  1.321194 -0.520746
10  0.303852  0.715404 -1.223223 -1.161968
11  0.642314  0.233722 -0.617865 -1.788715
12  0.260326  0.118854  1.715408 -0.566929
13 -0.280696  0.580446  1.114321  0.036158
14 -0.233312  0.013976 -0.891107  2.324843
15  0.230028 -0.456930 -0.391366  2.331580

In [ ]:
## To drop first row: don't run in case of pole embedding
#df = df.iloc[1: , :]
#df

In [ ]:
df.shape[0]

16

In [ ]:
Arr=np.zeros(df.shape[0])
Dolphin1=[50,35,13,39,59,4,15,21,9,31,60,48,37,1,46,16,24,16,29,19,41,56,12,52,5,38,22,30,54,44,36,17,45,53,34,15,43,11,46,15]
Dolphin2=[49,58,6,10,14,55,57,20,2,7,18,23,61,32,42,28,8,27,26]
Karate1=[13,20,5,6,1,4,3,17,7,11,12,22,18,8,2,14]
Karate2=[29,32,25,28,26,24,27,30,10,34,9,33,19,31,21,16,23,15]
Polbooks1=[17,16,38,39,37,44,26,18,14,45,30,33,3,2,6,57,23,53,59,78,25,50,56,20,35,40,42,55,36,43,28,24,9,12,13,34,27,22,46,58,48,40,15,51,54,21,46]
Polbooks2=[77,8,7,1,104,105,47,5,49,29,19,52,70]
Polbooks3=[99,93,79,32,76,84,92,88,101,63,91,82,80,83,72,98,85,75,83,72,64,61,100,74,73,31,86,60,97,87,71,67,69,102,90,89,94,81,65,62,96,95,68,103,66]
Highland1=[0,1,14,15]
Highland2=[4,8,9,12,13]
Highland3=[2,3,5,6,7,10,11]
XML1=[17,16,15]
XML2=[14,6,0]
XML3=[12,10,8,7,13,9,11]
XML4=[4,5,3,2,1]
for i in range(df.shape[0]):
   if(i in Highland1):
     Arr[i]=0
   elif(i in Highland2):
     Arr[i]=1
   elif(i in Highland3):
     Arr[i]=2
   #elif(i in XML4):
    # Arr[i]=4
df2=pd.DataFrame(Arr)


In [ ]:
Arr

array([0., 0., 2., 2., 1., 2., 2., 2., 1., 1., 2., 2., 1., 1., 0., 0.])

In [ ]:
Arr.shape

(16,)

In [ ]:
df.shape

(16, 4)

In [ ]:
df

0         1         2         3
0   0.424019  0.314390  0.171025  2.712381
1   0.250439  0.321740 -0.674131  2.353318
2  -0.203921 -0.370838 -0.380530 -1.772717
3  -0.078802 -0.265832 -0.226137 -0.885317
4  -0.064915  0.438161  1.092724 -1.580817
5  -0.016882  0.285393 -1.068567 -2.027799
6   0.231370  0.193363 -0.251585 -1.570515
7   0.305894 -0.313771 -1.044863 -1.561229
8   0.337618 -0.174567  1.724630 -0.581566
9   0.337390 -0.188121  1.321194 -0.520746
10  0.303852  0.715404 -1.223223 -1.161968
11  0.642314  0.233722 -0.617865 -1.788715
12  0.260326  0.118854  1.715408 -0.566929
13 -0.280696  0.580446  1.114321  0.036158
14 -0.233312  0.013976 -0.891107  2.324843
15  0.230028 -0.456930 -0.391366  2.331580

In [ ]:
from sklearn.cluster import KMeans
km = KMeans(n_clusters=3,init='k-means++')
km.fit(df)
c1=km.predict(df)

In [ ]:
c1

array([1, 1, 2, 2, 0, 2, 2, 2, 0, 0, 2, 2, 0, 0, 1, 1], dtype=int32)

In [ ]:
from sklearn.cluster import MiniBatchKMeans
km1 = MiniBatchKMeans(n_clusters=3)
km1.fit(df)
c2=km1.predict(df)

In [ ]:
c2

array([1, 1, 2, 2, 0, 2, 2, 2, 0, 0, 2, 2, 0, 0, 1, 1], dtype=int32)

In [ ]:
pip install kmodes

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
from kmodes.kmodes import KModes
km2 = KModes(n_clusters=3)
km2.fit(df)
c3=km2.predict(df)


In [ ]:
c3

array([0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint16)

In [ ]:
res_kmeans = {'NMI':normalized_mutual_info_score(c1, Arr),'Arr':adjusted_rand_score(Arr,c1)}
res_Mini_batch = {'NMI':normalized_mutual_info_score(c2, Arr),'Arr':adjusted_rand_score(Arr,c2)}
res_Kmodes = {'NMI':normalized_mutual_info_score(c3, Arr),'Arr':adjusted_rand_score(Arr,c3)}

In [ ]:
res_kmeans

{'NMI': 1.0, 'Arr': 1.0}

In [ ]:
res_Mini_batch

{'NMI': 1.0, 'Arr': 1.0}

In [ ]:
res_Kmodes

{'NMI': 0.1868279664199708, 'Arr': -0.001623000231857176}

In [ ]:
from scipy.spatial import distance

In [ ]:
from sklearn.cluster import SpectralClustering
from sklearn.metrics import confusion_matrix

In [ ]:
clustering = SpectralClustering(n_clusters=3,
assign_labels="discretize",random_state=0).fit(df)
    
M = confusion_matrix(Arr,clustering.labels_)
    
M

array([[0, 0, 4],
       [0, 5, 0],
       [7, 0, 0]])

In [ ]:
from sklearn.metrics import adjusted_rand_score
#adjusted_rand_score(Arr,clustering.labels_)
res_spect = {'NMI':normalized_mutual_info_score(clustering.labels_, Arr),'Arr':adjusted_rand_score(clustering.labels_,c1)}

In [ ]:
res_spect

{'NMI': 1.0, 'Arr': 1.0}

In [ ]:
distance.jaccard(Arr,clustering.labels_)

0.6875

In [ ]:
clustering.labels_

array([0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 0, 1, 1, 0, 0, 0, 1])

In [ ]:
from sklearn.metrics import davies_bouldin_score
davies_bouldin_score(df,clustering.labels_)

0.9049570106549357

In [ ]:
from sklearn.metrics.cluster import adjusted_mutual_info_score
adjusted_mutual_info_score(Arr,clustering.labels_)

0.3078877442870698

In [ ]:
from sklearn import metrics
metrics.homogeneity_score(Arr, clustering.labels_)

0.38888895648840505

In [ ]:
metrics.v_measure_score(Arr, clustering.labels_)

0.400465525154666

In [ ]:
metrics.homogeneity_completeness_v_measure(Arr,clustering.labels_)

(0.38888895648840505, 0.41275247040229607, 0.400465525154666)

In [ ]:
metrics.fowlkes_mallows_score(Arr,clustering.labels_)

0.2500965064695278

In [ ]:
from sklearn.cluster import AgglomerativeClustering 
hc = AgglomerativeClustering(n_clusters = 3, affinity = 'euclidean', linkage ='ward')
# Lets try to fit the hierarchical clustering algorithm  to dataset #X while creating the clusters vector that tells for each customer #which cluster the customer belongs to.
y_hc=hc.fit_predict(df)
y_hc

array([1, 1, 2, 2, 0, 2, 2, 2, 0, 0, 2, 2, 0, 0, 1, 1])

In [ ]:
res_hc = {'NMI':normalized_mutual_info_score(y_hc, Arr),'Arr':adjusted_rand_score(y_hc,c1)}
res_hc

{'NMI': 1.0, 'Arr': 1.0}

In [ ]:
pip install kmedoids 

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... error
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... error
     |████████████████████████████████| 354 kB 7.9 MB/s 


In [ ]:
pip install scikit-learn-extra

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 1.7 MB 5.3 MB/s 


In [ ]:
from sklearn_extra.cluster import KMedoids
import numpy as np

In [ ]:
kmedoids = KMedoids(n_clusters=2, random_state=0).fit(df)
kmedoids.labels_

array([0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0])

In [ ]:
res_km = {'NMI':normalized_mutual_info_score(kmedoids.labels_, Arr),'Arr':adjusted_rand_score(kmedoids.labels_,Arr)}
res_km

{'NMI': 0.6082818685553062, 'Arr': 0.5381984036488028}

In [ ]:
import numpy as np

from sklearn.cluster import DBSCAN
from sklearn import metrics
from sklearn.datasets import make_blobs
from sklearn.preprocessing import StandardScaler

In [ ]:
db = DBSCAN(eps=0.3, min_samples=10).fit(df)

In [ ]:
labels = db.labels_

# Number of clusters in labels, ignoring noise if present.
n_clusters_ = len(set(labels)) - (1 if -1 in labels else 0)
n_noise_ = list(labels).count(-1)

print("Estimated number of clusters: %d" % n_clusters_)
print("Estimated number of noise points: %d" % n_noise_)
print("Homogeneity: %0.3f" % metrics.homogeneity_score(Arr, labels))
print("Completeness: %0.3f" % metrics.completeness_score(Arr, labels))
print("V-measure: %0.3f" % metrics.v_measure_score(Arr, labels))
print("Adjusted Rand Index: %0.3f" % metrics.adjusted_rand_score(Arr, labels))
print(
    "Adjusted Mutual Information: %0.3f"
    % metrics.adjusted_mutual_info_score(Arr, labels)
)
#print("Silhouette Coefficient: %0.3f" % metrics.silhouette_score(df, labels))

Estimated number of clusters: 0
Estimated number of noise points: 16
Homogeneity: 0.000
Completeness: 1.000
V-measure: 0.000
Adjusted Rand Index: 0.000
Adjusted Mutual Information: 0.000


In [ ]:
df_spmf